# Generated by Django 3.2 on 2022-08-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220829_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock_amount',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
